FROM fedora:24
MAINTAINER Adam Samalik <asamalik@redhat.com>
ENV LANG=en_US.utf8

RUN dnf install -y python3-elasticsearch python3-fedmsg-core

ADD bpo-updater-fedmsg /code
WORKDIR /code/bpo-updater-fedmsg
CMD python3 -u updater.py
