FROM fedora:24
MAINTAINER Adam Samalik <asamalik@redhat.com>
ENV LANG=en_US.utf8

RUN dnf install -y python3-flask python3-elasticsearch

ADD bpo-web-ui /code
WORKDIR /code

EXPOSE 5000

CMD python3 -u app.py
